//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List()
        {
            this.User_List = new HashSet<User_List>();
        }
    
        public int ListID { get; set; }
        public string StartAdress { get; set; }
        public decimal StartPoint_x { get; set; }
        public decimal StartPoint_y { get; set; }
        public string EndAdress { get; set; }
        public decimal EndPoint_x { get; set; }
        public decimal EndPoint_y { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy年MM月dd日}")]
        public System.DateTime Departure_Date { get; set; }
        public System.TimeSpan Departure_Time { get; set; }
        public byte Sex { get; set; }
        public string Contacts { get; set; }
        public string detail { get; set; }
        public byte Statue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_List> User_List { get; set; }
    }
}
