//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List()
        {
            this.User_List = new HashSet<User_List>();
        }
    
        public int ListID { get; set; }
        public string StartAdress { get; set; }
        public int StartPoint_x { get; set; }
        public int StartPoint_y { get; set; }
        public string EndAdress { get; set; }
        public int EndPoint_x { get; set; }
        public int EndPoint_y { get; set; }
        public System.DateTime Departure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_List> User_List { get; set; }
    }
}
