//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;

    public partial class User_List
    {
        public int UserID { get; set; }
        public int ListID { get; set; }
        public System.DateTime Time { get; set; }
        // 1:发布 0：删除 2：收藏 3：取消收藏
        public byte Type { get; set; }
        public byte Status { get; set; }

        public virtual List List { get; set; }
        public virtual User User { get; set; }
    }
}
